import React from "react";
import Head from "next/head";

const Meta = () => {
  return (
    <Head>
      <title>Sholias LP</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"
      ></meta>
    </Head>
  );
};

export default Meta;
